### Get all users.
GET https://qu76blzmm7.execute-api.us-east-1.amazonaws.com/dev/user/
Accept: application/json
Authorization: Bearer {{auth_token}}

### Get specific user.
GET https://mg2wsml805.execute-api.us-east-1.amazonaws.com/dev/user/id?user_id={{id}}
Accept: application/json
Authorization: Bearer {{auth_token}}

### Create user.
POST  https://qu76blzmm7.execute-api.us-east-1.amazonaws.com/dev/user/
Accept: application/json
Content-Type: application/json

{
  "name": "{{username}}",
  "gender": "M",
  "birth_date": "2000-01-01",
  "password": "{{password}}"
}

### Delete current user.
DELETE https://qu76blzmm7.execute-api.us-east-1.amazonaws.com/dev/user/
Accept: application/json
Authorization: Bearer {{auth_token}}
