### Getting all articles
GET http://localhost:8000/article
Authorization: Bearer {{auth_token}}

### Creating an article
POST http://localhost:8000/article/
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "title": "TestingTitle",
  "body": "TestingBody"
}

### Deleting a specific article
DELETE http://localhost:8000/article/id?article_id={{id}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}
